apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::937240454358:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::937240454358:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OFER2ECYRPGT
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-05T13:35:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2065"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7feee09d-dcfb-4fbb-a485-51f1a1977a1f
